### ISSUE TITLE
Construct path with proper separator

### ISSUE THREAD

**Issue by devinivy** [devinivy/haute#2]
Right now we have a line that isn't very cross-OS friendly: https://github.com/devinivy/haute/blob/8014ec3996f0a2bffd7d7e5582b2c66a623330e6/lib/index.js#L26

**Comment by wswoodruff** [comment]
Can we just stringify __dirname and see which way the slashes go?

**Comment by devinivy** [comment]
There could be other oddities to take into account too.  In any case, nodejs worries about this for us with [`Path.join()`](https://nodejs.org/api/path.html#path_path_join_path1_path2) and `Path.sep`.
